CHANGELOG.md
authority-portal-frontend/src/app/common/components/form-elements/industry-select/industry-select.component.ts

closes #22 Register organization: Misplacement of "Other" Option in Industry Field Dropdown List
New order:
```[tasklist]
```

chore: change order of industry select options

---

CHANGELOG.md
authority-portal-frontend/src/app/core/utils/clipboard-utils.ts
authority-portal-frontend/src/app/pages/authority-connector-detail-page/authority-connector-detail-page/authority-connector-detail-page.component.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.ts
authority-portal-frontend/src/app/shared/components/business/connector-registering-success-message-page/connector-registering-success-message-page.component.ts
authority-portal-frontend/src/app/shared/components/business/shared-connector-detail/shared-connector-detail.component.ts

closes #24 Lack of Acknowledgement Message When Using Copy Icon
```[tasklist]
```

add notification on copy in connector details component

---

.github/markdown-link-checker-config.jq
CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/organizationmanagement/OrganizationInfoApiService.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/organizationmanagement/OrganizationInfoApiServiceTest.kt

Ordering of organizations

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/ComponentStatusApiService.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorMetadataService.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/utils/idmanagement/DataspaceComponentIdUtils.kt

Add provided connectors to dashboard

---

CHANGELOG.md
authority-portal-frontend/src/app/core/api/fake-backend/fake-backend.ts
authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form-model.ts
authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form.ts
authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page.component.html
authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page.component.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page-form-model.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page-form.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.html
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page-form-model.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page-form.ts
authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page.component.html
authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/organization-create-page/organization-create-page.component.html
authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/organization-create-page/organization-create-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/organization-create-page/organization-create-page.form-model.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.component.html
authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.form-mapper.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.form-model.ts

closes #121 Organisation registration - User can skip to step 3 and email sent message is displayed
"After filling in all details on the User Profile page and Org profile page, directly click on Email Verification from pagination, before clicking on the Register button.
It gives an acknowledgment message to verify email has been sent but no email appears and if navigate back it shows a yes tick mark. The email is sent only when the user clicks on the Register button.
Same behavior was observed in other components with mat-stepper:
+ create-organization
+ organization-onboarding
+ provide-connector
+ register-connector
+ register-central-component
"
```[tasklist]
```

Fix user can skip step

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/build.gradle.kts

This PR updates the Keycloak admin client library to enable updating Keycloak to 24.0.4
```[tasklist]
```

Keycloak update to 24.0.4

---

CHANGELOG.md
authority-portal-frontend/src/app/core/global-state/deployment-environment-url-sync.service.ts
authority-portal-frontend/src/app/core/global-state/global-state-utils.ts
authority-portal-frontend/src/app/core/global-state/routes/route-config-service.ts
authority-portal-frontend/src/app/pages/catalog-page/catalog-page/catalog-page.component.ts
authority-portal-frontend/src/app/shared/dev-utils/env-banner/env-banner.component.ts

URL will now contain e.g. `http://localhost:4200/catalog?environmentId=production`
it will disappear when navigating to a non-catalog page, a global solution has not been achieved yet, as that would require checking all links for queryParamsMerge

feat: catalog pages now sync deployment environment to url for better linkability

---

CHANGELOG.md
authority-portal-frontend/src/app/pages/authority-organization-list-page/authority-organization-list-page/authority-organization-list-page.component.ts

Closes #255 
```[tasklist]
```

fix: organization list not refreshing on environment change

---

CHANGELOG.md
authority-portal-frontend/src/app/pages/authority-organization-list-page/authority-organization-list-page/authority-organization-list-page.component.html

closes #286 UX of UI: Alignment on Organizations page of Data Offer Types
Old
New
```[tasklist]
```

chore: fix table header of Data Offer Types on Organizations page

---

CHANGELOG.md
authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.ts
authority-portal-frontend/src/app/shared/common/confirmation-dialog/confirmation-dialog.component.html
authority-portal-frontend/src/app/shared/common/confirmation-dialog/confirmation-dialog.component.ts

closes #305 Operator User - Flash message is not displayed while registering central components
closes #304 Operator user - delete and cancel confirmation popup window for the central components page frequently switches between the tabs
```[tasklist]
```

chore: fix delete and cancel buttons when deleting central components 

---

.github/workflows/license_scan.yml
.github/workflows/secret_scan.yml
.github/workflows/security_scan.yml

Trivy can run into db-download-rate limits using GitHub as DB host. A newer version now introduced db-caching and additionally a mirror of the original Trivy DBs is used instead of GitHub if running into GitHub rate limits.
```[tasklist]
```

fix(trivy): prevent rate-limit issues

---

authority-portal-backend/gradle/libs.versions.toml

This reverts commit 56bb1f0103c9219655841aceb2c6af80143c7af8.
The CVE this commit tried to remedy does not affect us, because we are not using Protobuf.
I would leave the version bump in, but unfortunately it breaks DAPS connectivity so I would avoid upgrading Quarkus when it is not absolutely necessary.

Revert "build(deps): update quarkus-bom (#342)"

---

CHANGELOG.md
authority-portal-frontend/src/app/core/api/fake-backend/impl/fake-users.ts
authority-portal-frontend/src/app/pages/authority-connector-list-page/authority-connector-list-page/authority-connector-list-page.component.ts
authority-portal-frontend/src/app/pages/authority-organization-list-page/authority-organization-list-page/authority-organization-list-page.component.ts
authority-portal-frontend/src/app/pages/catalog-page/catalog-page/catalog-page.component.ts
authority-portal-frontend/src/app/pages/central-component-list-page/central-component-list-page/central-component-list-page.component.ts
authority-portal-frontend/src/app/pages/control-center-organization-member-detail-page/control-center-organization-member-detail-page/control-center-organization-member-detail-page.component.ts
authority-portal-frontend/src/app/pages/control-center-organization-members-page/control-center-organization-members-page/control-center-organization-members-page.component.ts
authority-portal-frontend/src/app/pages/control-center-organization-profile-page/control-center-organization-profile-page/control-center-organization-profile-page.component.ts
authority-portal-frontend/src/app/pages/control-center-user-profile-page/control-center-user-profile-page/control-center-user-profile-page.component.ts
authority-portal-frontend/src/app/pages/dashboard-page/dashboard-page/dashboard-page.component.ts
authority-portal-frontend/src/app/pages/empty-pages/loading-page/loading-page/loading-page.component.ts
authority-portal-frontend/src/app/pages/empty-pages/page-not-found-page/page-not-found-page/page-not-found-page.component.ts
authority-portal-frontend/src/app/pages/empty-pages/unauthenticated-page/unauthenticated-page/unauthenticated-page.component.ts
authority-portal-frontend/src/app/pages/participant-own-connector-list-page/participant-own-connector-list-page/participant-own-connector-list-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-pending-page/organization-pending-page/organization-pending-page.component.ts
authority-portal-frontend/src/app/pages/registration-pages/organization-rejected-page/organization-rejected-page/organization-rejected-page.component.ts
authority-portal-frontend/src/app/pages/sp-connector-list-page/sp-connector-list-page/sp-connector-list-page.component.ts
authority-portal-frontend/src/app/shared/common/portal-layout/breadcrumb/breadcrumb.component.ts
authority-portal-frontend/src/app/shared/common/portal-layout/breadcrumb/breadcrumb.service.ts

closes #237 Website title does not update in some scenarios
Unauthenticated
Onboarding (both organization and user)
Pending
Rejected
404 Page not found (page + title)
Logged In
```[tasklist]
```

fix app title logic

---

CHANGELOG.md
authority-portal-frontend/src/app/core/api/fake-backend/fake-backend.ts
authority-portal-frontend/src/app/core/api/fake-backend/impl/fake-organizations.ts
authority-portal-frontend/src/app/core/api/fake-backend/impl/fake-users.ts
authority-portal-frontend/src/app/pages/authority-organization-detail-page/authority-organization-detail-page/authority-organization-detail-page.component.ts
authority-portal-frontend/src/app/pages/authority-organization-detail-page/state/authority-organization-detail-page-actions.ts
authority-portal-frontend/src/app/pages/authority-organization-detail-page/state/authority-organization-detail-page-state-impl.ts
docs/product/roles-and-rights/README.md

closes #287 Authority Section > Organizations > Users: live-update when deactivating/activating Users 
```[tasklist]
```

feat: live update after activate or deactivate user

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/build.gradle.kts
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/seeds/utils/ScenarioData.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/CaasManagementApiService.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/CaasManagementApiServiceTest.kt

fix: concurrency issues while requesting CaaS

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/seeds/DevScenario.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt

feat: add sorting to the list of connectors

---

CHANGELOG.md
authority-portal-backend/gradle/libs.versions.toml
docs/deployment-guide/goals/production/README.md

chore: release prep

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/utils/idmanagement/ClientIdUtils.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/CaasManagementApiServiceTest.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/ConnectorManagementApiServiceTest.kt

Closes #327 
```[tasklist]
```
This seems to be the only relevant piece of code to change. I decided to leave the function for generation in place, if there are changes to the generation of the clientId in the future, only this has to be changed again. Please provide feedback especially for the tests, if they make sense at all or maybe are at the wrong place.

feat: change client id generation for connectors central components

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/seeds/DevScenario.kt
authority-portal-backend/authority-portal-quarkus/src/main/resources/application.properties
authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.dev.json

This PR adds an Operator Admin user to the backend dev scenario/realm so that the Operator Admin in the user switcher from the frontend works.
```[tasklist]
```

fix: add operator admin to backend dev scenario/realm

---

CHANGELOG.md
authority-portal-frontend/src/app/app-routing.module.ts
authority-portal-frontend/src/app/core/services/config/app-config.ts
authority-portal-frontend/src/app/pages/control-center-user-edit-page/state/control-center-user-edit-page-state-impl.ts
authority-portal-frontend/src/app/shared/pipes-and-directives/external-url-directive.ts
authority-portal-keycloak/sovity-theme/login/login-update-password.ftl
authority-portal-keycloak/sovity-theme/login/password-commons.ftl
authority-portal-keycloak/sovity-theme/login/resources/css/login.css
authority-portal-keycloak/sovity-theme/login/theme.properties
docs/deployment-guide/goals/production/README.md

Password update function on user edit page

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/ConnectorManagementApiServiceTest.kt
authority-portal-frontend/src/app/pages/authority-connector-list-page/authority-connector-list-page/authority-connector-list-page.component.html

This PR removes the column with the link to the frontend URL to the connectors from the table of the all-connector-view of Authority- and Operator-Admins.
```[tasklist]
```

feat: remove frontend url column from all connectors-view for authority- and operator admins

---

.github/ISSUE_TEMPLATE/release.md
CHANGELOG.md
authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/ApiInformation.kt
authority-portal-backend/gradle/libs.versions.toml

Related: #399 
```[tasklist]
```

chore: release prep 5.0.0

---

CHANGELOG.md
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/AuthUtils.kt
authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/ConnectorManagementApiServiceTest.kt
authority-portal-frontend/src/app/pages/authority-connector-list-page/state/authority-connector-list-page-state-impl.ts

Deleting a connector from the `All Connectors` view as an Operator Admin resulted always in an error, this PR fixes this.
```[tasklist]
```

fix: allow operator admins to delete all connectors

---

.github/ISSUE_TEMPLATE/release.md
.github/markdown-link-checker-config.jq
README.md
authority-portal-backend/README.md
authority-portal-backend/authority-portal-api-client-ts/README.md
authority-portal-backend/authority-portal-api/README.md
authority-portal-backend/catalog-crawler/README.md
authority-portal-frontend/README.md
authority-portal-keycloak/README.md
authority-portal-oauth2-proxy/README.md
docs/deployment-guide/goals/production/README.md
docs/product/user-documentation/Authority Section.md
docs/product/user-documentation/General Overview.md
docs/product/user-documentation/Manage Data Space components.md

Changes all documentation I could find from **Authority Portal (AP)** to new **Data Space Portal (DSPortal)** naming.
```[tasklist]
```

docs: rebrand Authority Portal to Data Space Portal
