sovity/dataspace-portal

- CHANGELOG.md
- authority-portal-frontend/src/app/common/components/form-elements/certificate-input-form/certificate-input-form-builder.ts
- authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/request-connector-page/request-connector-page/request-connector-page-form.ts
- authority-portal-frontend/src/app/popups/authority-invite-new-organization/authority-invite-new-organization/authority-invite-new-organization.component.ts
- authority-portal-frontend/src/app/popups/participant-invite-new-user/participant-invite-new-user/participant-invite-new-user.component.ts
- authority-portal-frontend/src/app/shared/components/business/organization-create-form/organization-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/organization-edit-form/organization-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-create-form/user-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-edit-form/user-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-onboard-form/user-onboard-form-builder.ts
closes #17 Inconsistent Character Limit Implementation
```[tasklist]
```
> chore: update max length form field validations

- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/ComponentStatusApiService.kt
> 39 dashboard does not filter unknown connectors by mds

- CHANGELOG.md
- docs/deployment-guide/goals/production/README.md
> Fix placeholders for legal notice and privacy policy

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/uptimekuma/UptimeKumaClient.kt
- authority-portal-frontend/.env.local-dev
- authority-portal-frontend/.env.local-e2e-dev
- docs/deployment-guide/goals/production/README.md
> Fix Uptime Kuma response parsing

- CHANGELOG.md
- authority-portal-backend/authority-portal-api-client-ts/src/AuthorityPortalClient.ts
- authority-portal-backend/authority-portal-api-client-ts/vite.config.ts
- authority-portal-frontend/src/app/common/components/form-elements/certificate-input-form/certificate-input-form.component.html
- authority-portal-frontend/src/app/common/components/form-elements/connector-url-input/connector-url-input.component.html
- authority-portal-frontend/src/app/common/components/form-elements/connector-url-input/connector-url-input.component.ts
- authority-portal-frontend/src/app/common/components/form-elements/dsgvo-input/tos-check.component.html
- authority-portal-frontend/src/app/common/components/form-elements/industry-select/industry-select.component.html
- authority-portal-frontend/src/app/common/components/form-elements/industry-select/industry-select.component.ts
- authority-portal-frontend/src/app/common/components/form-elements/password-input/password-input.component.html
- authority-portal-frontend/src/app/common/components/form-elements/password-input/password-input.component.ts
- authority-portal-frontend/src/app/common/components/form-elements/password-repeat-input/password-repeat-input.component.html
- authority-portal-frontend/src/app/common/components/form-elements/password-repeat-input/password-repeat-input.component.ts
- authority-portal-frontend/src/app/common/components/form-elements/text-area/text-area.component.html
- authority-portal-frontend/src/app/common/components/form-elements/text-area/text-area.component.ts
- authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
- authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page.component.html
- authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.html
- authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page.component.html
- authority-portal-frontend/src/app/pages/component-registration-pages/request-connector-page/request-connector-page/request-connector-page.component.html
- authority-portal-frontend/src/app/popups/authority-invite-new-organization/authority-invite-new-organization/authority-invite-new-organization.component.html
- authority-portal-frontend/src/app/popups/participant-invite-new-user/participant-invite-new-user/participant-invite-new-user.component.html
- authority-portal-frontend/src/app/shared/components/business/organization-create-form/organization-create-form.component.html
- authority-portal-frontend/src/app/shared/components/business/organization-edit-form/organization-edit-form.component.html
- authority-portal-frontend/src/app/shared/components/business/user-create-form/user-create-form.component.html
- authority-portal-frontend/src/app/shared/components/business/user-edit-form/user-edit-form.component.html
- authority-portal-frontend/src/app/shared/components/business/user-onboard-form/user-onboard-form.component.html
> chore: added asterisks to required registration fields

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/sidebar/sidebar.component.ts
closes #52 Naming of Data Catalogue
```[tasklist]
```
> Renamed "All Data Offers" to "Data Catalogue"

- CHANGELOG.md
- authority-portal-frontend/src/app/pages/authority-organization-list-page/authority-organization-list-page/authority-organization-list-page.component.ts
> Fix 'invite participant' button for Authority Users

- CHANGELOG.md
- authority-portal-frontend/src/app/core/utils/address-utils.ts
> Fix organization address being displayed incorrectly

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/sidebar/sidebar.component.ts
> Changed mds logo redirect target

- CHANGELOG.md
- authority-portal-frontend/src/app/shared/components/business/shared-user-list/shared-user-list.component.html
> Added spaces between user roles

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/control-center/control-center.component.html
- authority-portal-frontend/src/app/shared/components/common/avatar/avatar.component.html
the button is now centered and looks good and consistent
the name and button are still highlited and have cursor pointer
no hover effect on hover of avatar (not possible to see on screenshot)
```[tasklist]
```
> Remove hover effect on avatar component and fix styles

- CHANGELOG.md
- authority-portal-keycloak/mds-theme/login/messages/messages_en.properties
> Changed wording to 'Reset password' on login page

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/breadcrumb/breadcrumb.service.ts
closes #54 Path is incorrect
```[tasklist]
```
> chore: remove control center from breadcrumbs path, append Changelog

- .github/ISSUE_TEMPLATE/release.md
- CHANGELOG.md
closes [#2](https://github.com/sovity/authority-portal-ee/issues/2)
```[tasklist]
```
> Adjust release issue template

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/AuthUtils.kt
- authority-portal-frontend/src/app/pages/authority-organization-detail-page/authority-organization-detail-page/authority-organization-detail-page.component.ts
> Fix user de-/reactivation

- CHANGELOG.md
- authority-portal-frontend/src/app/shared/services/certificate-generate.service.ts
> Fix certificate generation

- .github/ISSUE_TEMPLATE/release.md
Contributes to #88 
```[tasklist]
```
> Release cleanup

- CHANGELOG.md
- authority-portal-frontend/src/app/common/components/form-elements/connector-url-input/connector-url-input.component.ts
> Fixed Connector FE URL Placeholder

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/UiResource.java
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-frontend/src/app/core/api/api.service.ts
- authority-portal-frontend/src/app/pages/authority-connector-detail-page/state/authority-connector-detail-page-state-impl.ts
closes #119 
```[tasklist]
```
> Fix operator's all connectors list

- CHANGELOG.md
- authority-portal-keycloak/mds-theme/login/resources/css/login.css
- authority-portal-keycloak/mds-theme/login/template.ftl
> Legal notices on login page

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.dev.json
- authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.json
- docs/deployment-guide/goals/production/README.md
> Fixed "back to application" redirecting to login page

- authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/organization-create-page/organization-create-page.component.html
- authority-portal-frontend/src/app/pages/registration-pages/organization-onboard-page/organization-onboard-page/organization-onboard-page.component.html
closes #136 
```[tasklist]
```
> Update organization-create-page and organization-onboard-page HTML

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/redirects/BrokerRedirectApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/BrokerClient.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/BrokerClientResource.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/BrokerSyncService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/README.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/model/AddedConnector.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/broker/model/ConnectorCreationRequest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/connectormanagement/ConnectorManagementApiServiceTest.kt
- authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/organization-create-page/organization-create-page.component.html
Contributes to #44
```[tasklist]
```
> Fix redirect to own data offers

- CHANGELOG.md
- authority-portal-backend/authority-portal-db/src/main/resources/db/migration/V8__Schema_Extension.sql
- authority-portal-backend/authority-portal-db/src/main/resources/db/testdata/V1_1__Initial_Schema_Test_Data.sql
- authority-portal-backend/authority-portal-db/src/main/resources/db/testdata/V7_2__Fix_for_user_table.sql
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UnconfirmedUserDeletionService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UserDeletionApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/UserService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.dev.json
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/usermanagement/UserDeactivationApiServiceTest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/usermanagement/UserDeletionApiServiceTest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/thirdparty/broker/BrokerSyncServiceTest.kt
> Fix user deletion

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/ComponentStatusApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt
closes #118 
```[tasklist]
```
> Fix dashboard connector status calculation

- CHANGELOG.md
> Release 2.1.2 prep

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/sidebar/sidebar.component.ts
closes #117 
```[tasklist]
```
> Adjust wording in sidebar

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/ConfigResource.java
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/UiResource.java
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/ConfigResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/ConfigApiKeyFilter.kt
- authority-portal-backend/authority-portal-quarkus/src/main/resources/application.properties
- docs/deployment-guide/goals/production/README.md
> Add endpoint to change log level

- CHANGELOG.md
- authority-portal-keycloak/mds-theme/email/html/password-reset.ftl
- authority-portal-keycloak/mds-theme/email/messages/messages_en.properties
closes #116 
```[tasklist]
```
> Adjust wording in reset password email

- CHANGELOG.md
- authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.html
closes #112 
```[tasklist]
```
> Fix wording on "Provide Central Component" form

- CHANGELOG.md
- authority-portal-frontend/src/app/common/layouts/portal-layout/control-center/control-center.component.html
- authority-portal-frontend/src/app/core/utils/string-utils.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page.component.html
- authority-portal-frontend/src/app/pages/control-center-organization-member-detail-page/control-center-organization-member-detail-page/control-center-organization-member-detail-page.component.html
- authority-portal-frontend/src/app/pages/control-center-organization-member-detail-page/state/control-center-organization-member-detail-page-state-impl.ts
- authority-portal-frontend/src/app/pages/control-center-organization-members-page/control-center-organization-members-page/control-center-organization-members-page.component.ts
- authority-portal-frontend/src/app/pages/control-center-page/control-center-routes.ts
- authority-portal-frontend/src/app/pages/dashboard-page/dashboard-csv-reports-card/dashboard-csv-reports-card.component.ts
- docs/product/user-documentation/Administration and Support.md
- docs/product/user-documentation/Manage Data Space components.md
closes #150 Wrong Path - Users&Roles
```[tasklist]
```
> 150 wrong path   usersroles

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/CaasManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UserUpdateApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CentralComponentService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/OrganizationService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/UserService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/keycloak/KeycloakService.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/TestData.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/organizationmanagement/OrganizationUpdateApiServiceTest.kt
- authority-portal-frontend/src/app/common/components/form-elements/text-area/text-area.component.html
- authority-portal-frontend/src/app/core/utils/validators/phone-number-validator.ts
- authority-portal-frontend/src/app/popups/authority-invite-new-organization/authority-invite-new-organization/authority-invite-new-organization.component.ts
- authority-portal-frontend/src/app/shared/components/business/organization-create-form/organization-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/organization-edit-form/organization-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-create-form/user-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-edit-form/user-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-onboard-form/user-onboard-form-builder.ts
closes #161 Form validators need to be fixed
```[tasklist]
```
> fix phone number and description validators

- CHANGELOG.md
- authority-portal-frontend/src/app/app-routing.module.ts
closes #163 Page not found "MyUsers"
```[tasklist]
```
> fix: add users-and-roles routing redirect

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/AuthUtils.kt
- authority-portal-frontend/src/app/pages/authority-organization-detail-page/authority-organization-detail-page/authority-organization-detail-page.component.ts
- authority-portal-frontend/src/app/pages/control-center-organization-member-detail-page/state/control-center-organization-member-detail-page-state-impl.ts
- authority-portal-frontend/src/app/pages/control-center-user-profile-page/control-center-user-profile-page/control-center-user-profile-page.component.ts
- authority-portal-frontend/src/app/pages/control-center-user-profile-page/state/control-center-user-profile-page-action.ts
- authority-portal-frontend/src/app/pages/control-center-user-profile-page/state/control-center-user-profile-page-state-impl.ts
- authority-portal-frontend/src/app/shared/components/common/title-bar/title-bar.component.ts
closes #127 
```[tasklist]
```
> Add self-deletion for users

- CHANGELOG.md
- authority-portal-keycloak/mds-theme/login/resources/css/login.css
closes #165 Logo cutoff
```[tasklist]
```
> fix: keycloak

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/connectormanagement/ConnectorManagementApiServiceTest.kt
closes #172 
```[tasklist]
```
> Fix "Provided Connectors" view

- CHANGELOG.md
- docs/deployment-guide/goals/production/Caddyfile
closes #176 
```[tasklist]
```
> Modify headers for security

- CHANGELOG.md
- authority-portal-backend/gradle.properties
This PR updates the used quarkus version and patches CVE-2024-2700.
```[tasklist]
```
> chore: patch CVE-2024-2700

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/CaasManagementApiService.kt
closes #196 
```[tasklist]
```
> Fix error message for existing subdomains

- CHANGELOG.md
- authority-portal-frontend/src/app/core/utils/connector-config-utils.ts
> Fix naming of EDC variable

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/reporting/ConnectorAuthorityCsvReportService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/reporting/ConnectorParticipantCsvReportService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/reporting/utils/ConnectorCsvReportUtils.kt
Closes #189 
```[tasklist]
```
> Added connector status to CSV report

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
> Show DEAD connectors as OFFLINE in the FE

- CHANGELOG.md
- authority-portal-frontend/.env.local-dev
- authority-portal-frontend/.env.local-e2e-dev
- authority-portal-frontend/src/app/common/layouts/portal-layout/sidebar/sidebar.component.ts
- authority-portal-frontend/src/app/core/config/app-config.ts
- docs/deployment-guide/goals/production/README.md
Closes #203 
```[tasklist]
```
> Configurable support URL

- CHANGELOG.md
- authority-portal-frontend/package-lock.json
- authority-portal-keycloak/mds-theme/login/template.ftl
- authority-portal-keycloak/mds-theme/login/theme.properties
> Release prep - 2.3.0

- authority-portal-backend/authority-portal-quarkus/src/main/docker/Dockerfile.jvm
Updates the used base image from ubi8 to ubi9.
> build: update base-image to ubi9

- CHANGELOG.md
- authority-portal-frontend/src/app/core/utils/time-utils.ts
Closes #211 
```[tasklist]
```
> Limit uptime display if longer than 30 days

- CHANGELOG.md
- authority-portal-frontend/src/app/common/components/form-elements/certificate-input-form/certificate-input-form-builder.ts
- authority-portal-frontend/src/app/common/components/form-elements/text-area/text-area.component.html
- authority-portal-frontend/src/app/common/components/form-elements/text-input/text-input.component.html
- authority-portal-frontend/src/app/core/utils/validators/not-blank-validator.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-central-component-page/register-central-component-page/register-central-component-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/request-connector-page/request-connector-page/request-connector-page-form.ts
- authority-portal-frontend/src/app/popups/authority-invite-new-organization/authority-invite-new-organization/authority-invite-new-organization.component.ts
- authority-portal-frontend/src/app/popups/participant-invite-new-user/participant-invite-new-user/participant-invite-new-user.component.ts
- authority-portal-frontend/src/app/shared/components/business/organization-create-form/organization-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/organization-edit-form/organization-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-create-form/user-create-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-edit-form/user-edit-form-builder.ts
- authority-portal-frontend/src/app/shared/components/business/user-onboard-form/user-onboard-form-builder.ts
- authority-portal-frontend/src/styles.css
closes #193 Error message vague for various validation issues on CaaS request 
it fixes same issues across the whole app
```[tasklist]
```
> Add "string not blank when trimmed" validator 

- authority-portal-backend/authority-portal-quarkus/src/main/docker/Dockerfile.jvm
Patches base-image to newest UBI8 image.
```[tasklist]
```
> build: update base-image to newest ubi8

- authority-portal-frontend/docker/Dockerfile
Updates the base image of the front end.
```[tasklist]
```
> Update Dockerfile Base-Image

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/model/ProvidedConnectorOverviewEntryDto.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/CaasManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/OrganizationService.kt
- docs/product/user-documentation/Administration and Support.md
Closes #206 
```[tasklist]
```
> Fix CaaS not showing up in provided connectors and provider ID not displaying

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/UiResource.kt
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/model/CreateConnectorResponse.kt
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/model/CreateConnectorWithJwksRequest.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/model/ConnectorCreationData.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/model/CreateConnectorParams.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/CaasManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorManagementApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/connector/ConnectorManagementApiServiceTest.kt
- authority-portal-frontend/src/app/core/api/api.service.ts
- authority-portal-frontend/src/app/core/api/fake-backend/fake-backend.ts
- authority-portal-frontend/src/app/core/api/fake-backend/impl/fake-connectors.ts
- authority-portal-frontend/src/app/core/services/certificate-generate.service.ts
- authority-portal-frontend/src/app/core/utils/connector-config-utils.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form-enabled-ctrls.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form-model.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page-form.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page.component.html
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/provide-connector-page/provide-connector-page.component.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/state/provide-connector-page-actions.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/provide-connector-page/state/provide-connector-page-state-impl.ts
- authority-portal-frontend/src/app/pages/component-registration-pages/register-connector-page/register-connector-page/register-connector-page.component.ts
- authority-portal-frontend/src/app/shared/business/connector-registering-success-message-page/connector-registering-success-message-page.component.html
- authority-portal-frontend/src/app/shared/form-elements/certificate-input-form/certificate-input-form.component.ts
> Jwks connector provide

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/connectormanagement/ConnectorStatusMapper.kt
- authority-portal-frontend/src/app/core/utils/ui-utils.ts
Closes #270 
```[tasklist]
```
> Connector status wording

- authority-portal-frontend/docker/Dockerfile
Updates the base image.
```[tasklist]
```
> chore(docker): update base image

- .github/workflows/codeql.yml
Adds advanced configuration for CodeQL analysis.
```[tasklist]
```
> feat(codeql): add advanced configuration for CodeQL analysis

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/reporting/DataOfferCsvReportService.kt
Closes #283 
Closes #292
Includes a small non-user-facing bugfix
```[tasklist]
```
> Data Offer CSV Export LIVE -> Available

- CHANGELOG.md
- authority-portal-frontend/src/app/core/services/error.service.ts
- authority-portal-frontend/src/app/pages/authority-organization-list-page/authority-invite-new-organization/state/authority-invite-new-organization-page-state-impl.ts
- authority-portal-frontend/src/app/pages/control-center-organization-members-page/participant-invite-new-user/state/participant-invite-new-user-page-state-impl.ts
- authority-portal-frontend/src/app/pages/registration-pages/organization-create-page/state/organization-create-page-state-impl.ts
Closes #290 
```[tasklist]
```
> fix: vague error message on 409 from KC

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/model/UserDeletionCheck.kt
> Fix: Last User Deletion

- authority-portal-backend/authority-portal-api-client-ts/package-lock.json
- authority-portal-frontend/package-lock.json
> chore(deps): bumped micromatch to 4.0.8

- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/reporting/DataOfferCsvReportService.kt
Closes #314 
```[tasklist]
```
> fix: CaasUpdateService now disables correctly

- CHANGELOG.md
- authority-portal-backend/gradle/libs.versions.toml
- docs/deployment-guide/goals/production/README.md
> Release 4.1.1

- CHANGELOG.md
- docs/product/user-documentation/Manage Data Space components.md
> Docs: Add commands to generate a X.509 certificate locally

- CHANGELOG.md
- authority-portal-frontend/docker/Dockerfile
- authority-portal-frontend/docker/default.conf.template
- authority-portal-frontend/src/app/core/services/config/app-config-initializer.ts
Closes #322 
```[tasklist]
```
> fix: invalid configuration after version upgrade

- authority-portal-backend/gradle/libs.versions.toml
update quarkus-bom dependency
```[tasklist]
```
> build(deps): update quarkus-bom

- CHANGELOG.md
- authority-portal-frontend/src/app/pages/control-center-organization-members-page/control-center-organization-members-page/control-center-organization-members-page.component.ts
- authority-portal-frontend/src/app/pages/control-center-organization-profile-page/control-center-organization-profile-page/control-center-organization-profile-page.component.ts
- authority-portal-frontend/src/app/pages/control-center-user-profile-page/control-center-user-profile-page/control-center-user-profile-page.component.ts
closes #255 Organizations-page not updated when switching between environments 
```[tasklist]
```
> feat: refresh on environment switch in control center

- CHANGELOG.md
- authority-portal-frontend/package-lock.json
Fixes security vulnerabilities and GH Actions' Markdown Link Checks
Old Link
```[tasklist]
```
> fix: security

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/organizationmanagement/OrganizationInvitationApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/registration/RegistrationApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UserInvitationApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/UserService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/keycloak/KeycloakService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/thirdparty/uptimekuma/model/ComponentStatus.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/utils/HttpExceptionUtils.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/FirstUserRegistrationTest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/RegistrationApiServiceTest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/organization/OrganizationInvitationApiServiceTest.kt
> fix: made portal db the source of truth on user creation

- CHANGELOG.md
- authority-portal-backend/authority-portal-db/src/main/resources/db/migration/V12__Fix_Service_Provider_User_Deletion.sql
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UserDeletionApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/ConnectorService.kt
> fix: user deletion

- CHANGELOG.md
- authority-portal-backend/authority-portal-quarkus/src/main/resources/application.properties
- authority-portal-backend/authority-portal-quarkus/src/main/resources/realm.dev.json
- authority-portal-backend/docs/dev/keycloak-realm-export/README.md
The Keycloak dev realm is out of sync with the local E2E configuration. This PR configures the Keycloak dev realm, so that it works with the local E2E development setup and the User Switcher of the frontend.
```[tasklist]
```
> fix: fix keycloak dev realm

- docs/product/user-documentation/Authority Section.md
- docs/product/user-documentation/Manage Data Space components.md
Closes #407 
Don't worry about PR checks, target branch is "gitbook" and thus it updates our live GitBook documentation about the AP.
```[tasklist]
```
> chore(docs): add connector type and status documentation

- CHANGELOG.md
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/UiResource.kt
- authority-portal-backend/authority-portal-api/src/main/java/de/sovity/authorityportal/api/model/organization/OrganizationDeletionCheck.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/AuthUtils.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/auth/LoggedInUserFactory.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/organizationmanagement/OrganizationDeletionApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/pages/usermanagement/UserDeletionApiService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/OrganizationDeletionService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/UserDeletionService.kt
- authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/UserService.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/organization/OrganizationDeletionApiServiceTest.kt
- authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/tests/services/user/UserDeletionApiServiceTest.kt
- authority-portal-frontend/src/app/core/api/api.service.ts
- authority-portal-frontend/src/app/pages/authority-organization-detail-page/authority-organization-detail-page/authority-organization-detail-page.component.ts
- authority-portal-frontend/src/app/shared/business/organization-delete-dialog/organization-delete-dialog.component.html
- authority-portal-frontend/src/app/shared/business/organization-delete-dialog/organization-delete-dialog.component.ts
- authority-portal-frontend/src/app/shared/business/organization-delete-dialog/organization-delete-dialog.model.ts
- authority-portal-frontend/src/app/shared/business/organization-delete-dialog/organization-delete-dialog.service.ts
- authority-portal-frontend/src/app/shared/business/user-delete-dialog/user-delete-dialog.component.html
- authority-portal-frontend/src/app/shared/shared.module.ts
This PR introduces the ability for Authority Admins to delete an organization.
```[tasklist]
```
> feat: organization deletion

- .github/DISCUSSION_TEMPLATE/general.yml
- .github/DISCUSSION_TEMPLATE/ideas.yml
- .github/DISCUSSION_TEMPLATE/q-a.yml
> Discussions Templates
